[package]
name = "wire"
version = "0.1.0"
authors = ["Parker Huntington <huntingt@mit.edu>"]
edition = "2018"

[dependencies]
chrono-tz = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
